-- QUERIES

-- LINK TO ACCESS DATABASE
-- https://learn.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-ver16&tabs=ssms
-- FILE NAME: AdventureWorksLT2022.bak (LIGHTWEIGHT)

USE AdventureWorksLT2022;

-- 1. SELECT QUERY
SELECT * FROM SALESLT.PRODUCT;
SELECT PRODUCTID AS ID, NAME, PRODUCTNUMBER, LISTPRICE, COLOR FROM SalesLT.Product;

-- 2. DISTINCT QUERY (EXTRACTS UNIQUE VALUES)
SELECT DISTINCT PRODUCTNUMBER FROM SalesLT.Product;
SELECT DISTINCT COLOR, PRODUCTNUMBER FROM SalesLT.Product;

--3. DISTINCT WITH COUNT(COUNT IS A FUNCTION AND DISTINCT IS A KEYWORD)
SELECT COUNT(DISTINCT COLOR) FROM SalesLT.Product;
SELECT COUNT(DISTINCT SIZE) FROM SalesLT.Product;

--4 WHERE CLAUSE (CONDITION USED WITH UPDATE, DELETE AND SELECT QUERIES)
SELECT * FROM SalesLT.Product WHERE COLOR = 'BLACK';
SELECT * FROM SalesLT.Product WHERE SIZE IS NULL;
SELECT * FROM SalesLT.Product WHERE ListPrice > 3000;
SELECT * FROM SalesLT.Product WHERE ListPrice BETWEEN 500 AND 1000;
SELECT * FROM SalesLT.Product WHERE NAME LIKE '%ROAD%';
SELECT * FROM SalesLT.Product WHERE COLOR IN ('BLACK','RED');
SELECT * FROM SalesLT.Product WHERE ListPrice != 1431.50;
--WITH SELECT WEHRE CAN BE USED WITH OPERATORS: =, <, >, >=, <=, !=, BETWEEN, LIKE, IN

--5 ORDER BY (USED TO SORT THE RESULT IN ASCENDING OR DESCENDING ORDER)
SELECT * FROM SalesLT.Product ORDER BY ListPrice DESC;
SELECT * FROM SalesLT.Product ORDER BY ListPrice ASC;
SELECT * FROM SalesLT.Product ORDER BY NAME ASC;
SELECT * FROM SalesLT.Product ORDER BY NAME ASC, ProductNumber DESC;

--6 AND OPERATOR 
SELECT * FROM SalesLT.PRODUCT WHERE SIZE IS NULL AND Weight IS NULL;

--7 OR OPERATOR
SELECT * FROM SalesLT.Product WHERE NAME LIKE '%S' OR ProductNumber LIKE '%H';

--8 NOT
SELECT * FROM SalesLT.Product WHERE NOT COLOR = 'black'; 

--9 INSERT INTO 
--INSERT INTO TABLE_NAME(COLUMN1, COLUMN2, COLUMN3) VALUES (VALUE1, VALUE2, VALUE3);
